homepage/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from . import views
from .sitemaps import HomepageSitemap

app_name = 'homepage'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': {'homepage': HomepageSitemap}},
        name='django.contrib.sitemaps.views.sitemap',
    ),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('support/', include('support.urls', namespace='support')),
]

support/urls.py
from django.urls import path

from . import views

app_name = 'support'

urlpatterns = [
    path('contact/', views.save_contact_form, name='save_contact_form'),
    path('signup/', views.save_newsletter_signup, name='save_newsletter_signup'),
]

accounts/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        ordering = ['email']

homepage/models.py
from django.db import models

# Create your models here.

support/models.py
from django.db import models

# Create your models here.


class ContactForm(models.Model):
    sender_name = models.CharField(max_length=150)
    sender_phone = models.CharField(max_length=15)
    message_subject = models.CharField(max_length=150)
    message_text = models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender_name


class Newsletter(models.Model):
    user_email = models.EmailField()
    registered_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user_email

accounts/views.py
from django.shortcuts import render

# Create your views here.

homepage/views.py
from django.views.generic import TemplateView

# Create your views here.


class HomePageView(TemplateView):
    template_name = 'homepage/index.html'

support/views.py
from django.http import JsonResponse
from django.utils.html import escape

from .models import ContactForm, Newsletter

# Create your views here.


def save_contact_form(request):
    if request.method == 'POST':
        sender_name = escape(request.POST.get('sender_name'))
        sender_phone = escape(request.POST.get('sender_phone'))
        message_subject = escape(request.POST.get('message_subject'))
        message_text = escape(request.POST.get('message_text'))

        contact_form = ContactForm(
            sender_name=sender_name,
            sender_phone=sender_phone,
            message_subject=message_subject,
            message_text=message_text,
        )
        contact_form.save()

        return JsonResponse({'success': 'true'})


def save_newsletter_signup(request):
    if request.method == 'POST':
        user_email = escape(request.POST.get('user_email'))

        newsletter = Newsletter(user_email=user_email)
        newsletter.save()

        return JsonResponse({'success': 'true'})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa-IR">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="شرکت آرتا شبکه یک پیشرو در زمینه خدمات شبکه و فناوری اطلاعات (آی تی) است که با سابقه‌ی بیش از ده سال سابقه‌ی درخشان، به عنوان یکی از بهترین انتخاب‌ها برای تامین نیازهای شبکه و فناوری اطلاعات سازمان‌ها و شرکت‌ها شناخته می‌شود. آرتا شبکه با تیمی متخصص و مجرب از متخصصان IT و شبکه، خدمات گسترده‌ای ارائه می‌دهد، از جمله طراحی و پیاده‌سازی شبکه‌های مخابراتی و دیتاسنترها، مدیریت شبکه و امنیت اطلاعات، توسعه نرم‌افزارهای سفارشی، و پشتیبانی فنی 24/7. آرتا شبکه با تمرکز بر رضایت مشتریان و به‌کارگیری تکنولوژی‌های نوین، به شرکت‌ها کمک می‌کند تا عملکرد خود را بهبود دهند و در دنیای رقابتی فعلی، تجربه‌ی شبکه و آی تی بهبود یابد.">

        <title>{% block title %}{% endblock %}</title>

        <!-- Favicons -->

        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100;200;300;400;500;600;700;800;900&display=swap">

        <!-- Vendor CSS Files -->
        <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.rtl.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/glightbox/css/glightbox.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/swiper/swiper-bundle.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendor/aos/aos.css' %}">

        <!-- Template CSS Files -->
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

    </head>

    <body class="index-page" data-bs-spy="scroll" data-bs-target="#navmenu">
    <!-- ======= Header ======= -->
        <header id="header" class="header fixed-top d-flex align-items-center">
            <div class="container-fluid d-flex align-items-center justify-content-between">

                <a href="{% url 'homepage:index' %}" class="logo d-flex align-items-center me-auto me-xl-0">
                    <h1>آرتا شبکه</h1>
                    <span>.</span>
                </a>

                <!-- Nav Menu -->
                <nav id="navmenu" class="navmenu">
                    <ul>
                        <li><a href="{% url 'homepage:index' %}" class="active">خانه</a></li>
                        <li><a href="{% url 'homepage:index' %}#about">درباره ما</a></li>
                        <li><a href="{% url 'homepage:index' %}#tower">دکل مخابراتی</a></li>
                        <li><a href="{% url 'homepage:index' %}#hardware">سخت‌افزار شبکه</a></li>
                        <li><a href="{% url 'homepage:index' %}#software">خدمات نرم‌افزاری</a></li>
                    </ul>
                    <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
                </nav><!-- End Nav Menu -->

                <a class="btn-getstarted" href="https://artanetwork.com/downloads/ipr.exe">دانلود Iperius Remote</a>
                <a class="btn-getstarted" href="{% url 'homepage:index' %}#contact">تماس با ما</a>
                
            </div>
        </header><!-- End Header-->

        {% block content %}{% endblock %}

        <!-- ======= Footer ======= -->
        <footer id="footer" class="footer">

            <div class="container footer-top">
                <div class="row gy-4">
                    <div class="col-lg-5 col-md-12 footer-about">
                        <a href="{% url 'homepage:index' %}" class="logo d-flex align-items-center">
                            <span>آرتا شبکه</span>
                        </a>
                        <p>ارائه‌دهنده خدمات دکل مهاری، شبکه، سرور، نرم‌افزار، دوربین، امنیت، VoIP، طراحی سایت و تولید اپلیکیشن</p>
                        <div class="social-links d-flex mt-4">
                            <a href="https://instagram.com/arta_network" target="_blank"><i class="bi bi-instagram"></i></a>
                            <a href="https://wa.me/989935530200/" target="_blank"><i class="bi bi-whatsapp"></i></a>
                            <a href="https://ta.me/+989935530200/" target="_blank"><i class="bi bi-telegram"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-2 col-6 footer-links">
                        <h4>خدمات ما</h4>
                        <ul>
                            <li><a href="{% url 'homepage:index' %}#tower">دکل مخابراتی</a></li>
                            <li><a href="{% url 'homepage:index' %}#hardware">سخت‌افزار شبکه</a></li>
                            <li><a href="{% url 'homepage:index' %}#software">خدمات نرم‌افزاری</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
                        <h4>تماس با ما</h4>
                        <p>میدان هفت تیر، خیابان مشاهیر، خیابان زیبا، خیابان مروارید، پلاک ۴، واحد ۲</p>
                        <p class="mt-4"><strong>تلفن:</strong> <span>۰۲۱-۹۲۰۰۱۳۹۲</span></p>
                        <p><strong>ایمیل:</strong> <span>info@artanetwork.com</span></p>
                    </div>

                </div>
            </div>

            <div class="container copyright text-center mt-4">
                <p>تمامی حقوق برای آرتا شبکه صنعت رایان محفوظ است. نقل مطالب با ذکر منبع آزاد است.</p>
                <div class="credits">
                    طراحی و اجرا توسط آرتا شبکه صنعت رایان
                </div>
            </div>

        </footer><!-- End Footer -->

        <!-- Scroll Top Button -->
        <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

        <!-- Preloader -->
        <div id="preloader">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>

        <!-- Vendor JS Files -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
        <script src="{% static 'vendor/purecounter/purecounter_vanilla.js' %}"></script>
        <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>
        <script src="{% static 'vendor/aos/aos.js' %}"></script>

        <!-- Template JS Files -->
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/load.csrf.token.js' %}"></script>
        <script src="{% static 'js/submit.contact.form.js' %}"></script>
        <script src="{% static 'homepage/js/save.newsletter.signup.js' %}"></script>
    </body>
</html>